version: "3.8"
name: durian-robot
services:
  ros2:
    build:
      context: ./
      args:
        - user_id=1000
        - ros_ws=/home/dev_ws
        # - ros_gz_ws=/home/ros_gz_ws
    image: durian-robot-ros2

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - ROS_DOMAIN_ID=21
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - GZ_VERSION=garden
      - TERM=xterm-256color
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR='/tmp/runtime-root'
      - PULSE_SERVER
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MAKEFLAGS="-j 4"

    volumes:
      - ./:/home/project
      - ./dev_ws:/home/dev_ws  
      # - ./ros_gz_ws:/home/ros_gz_ws
      - ./docker/ros2/.ros:/home/.ros

    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    stop_grace_period: 1s

  dev:
    extends:
      service: ros2
    profiles:
      - dev
    restart: always